apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: homes.smarthome.mock.digi.dev
spec:
  group: smarthome.mock.digi.dev
  names:
    kind: Home
    listKind: HomeList
    plural: homes
    singular: home
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              control:
                properties:
                  mode:
                    properties:
                      intent:
                        type: string
                      status:
                        type: string
                    type: object
                type: object
              mount:
                properties:
                  smarthome.mock.digi.dev/v1/rooms:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            control:
                              properties:
                                brightness:
                                  properties:
                                    intent:
                                      type: number
                                    status:
                                      type: number
                                  type: object
                              type: object
                            meta:
                              properties:
                                load_interval:
                                  type: number
                              type: object
                            mount:
                              properties:
                                smarthome.mock.digi.dev/v1/lamps:
                                  additionalProperties:
                                    properties:
                                      generation:
                                        type: number
                                      mode:
                                        type: string
                                      spec:
                                        properties:
                                          control:
                                            properties:
                                              brightness:
                                                properties:
                                                  intent:
                                                    type: number
                                                  status:
                                                    type: number
                                                type: object
                                            type: object
                                          meta:
                                            properties:
                                              load_interval:
                                                type: number
                                            type: object
                                        type: object
                                      status:
                                        type: string
                                    type: object
                                  type: object
                              type: object
                            obs:
                              properties:
                                human_presence:
                                  type: boolean
                                objects:
                                  items:
                                    properties:
                                      activity:
                                        type: string
                                      class:
                                        type: string
                                      name:
                                        type: string
                                    type: object
                                  type: array
                              type: object
                            reflex:
                              additionalProperties:
                                properties:
                                  policy:
                                    type: string
                                  priority:
                                    type: number
                                  processor:
                                    type: string
                                type: object
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                type: object
              obs:
                properties:
                  rooms:
                    additionalProperties:
                      properties:
                        brightness:
                          type: number
                        objects:
                          items:
                            properties:
                              activity:
                                type: string
                              class:
                                type: string
                              name:
                                type: string
                            type: object
                          type: array
                      type: object
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
