apiVersion: deid.demo.digi.dev/v1
kind: Lamp
metadata:
  name: {{ .Values.name }}
spec:
  control:
    # default settings
    power:
      intent: "off"
    brightness:
      intent: 0.2
  meta:
    wattage: 12
    report_interval: -1
    auto_brightness: false
  # data router configs
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
