apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: offices.lifelogging.demo.digi.dev
spec:
  group: lifelogging.demo.digi.dev
  names:
    kind: Office
    listKind: OfficeList
    plural: offices
    singular: office
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties: {}
            type: object
        type: object
    served: true
    storage: true
